### ISSUE TITLE
The workspace metadata sometimes gets corrupted

### ISSUE THREAD

**Issue by reprogrammer** [vazexqi/CodingSpectator#276] opened 2011-07-10 19:42 UTC
We've received reports about two incidents where the workspace metadata got corrupted. In the first case, Eclipse hung during the data upload. And, in the second case, Eclipse hung at startup while loading up the `org.eclipse.jdt.ui` plug-in. In both cases, the workspace got corrupted.

This is a serious issue because it causes data loss to our users and gives them a bad experience.

**Comment by reprogrammer** [comment] 2011-07-11 06:04
@Wanderer777: One of our participants reported that his Eclipse hung while loading `org.eclipse.jdt.ui`. Our only change to loading `org.eclipse.jdt.ui` is to load up CodingTracker in `org.eclipse.jdt.internal.ui.JavaPlugin.start(BundleContext)`. If you know of any other possible causes of the problem in loading `org.eclipse.jdt.ui` please let us know.

I have the following suggestion for finding and fixing the problem in loading `org.eclipse.jdt.ui`.
1. Change `org.eclipse.jdt.internal.ui.JavaPlugin.notifyStartupListeners()` to invoke `org.eclipse.jdt.internal.ui.startup.StartupListener.jdtuiIsAboutToStart()` using a `org.eclipse.core.runtime.SafeRunner` to protected against possible exceptions.
2. Make sure that the calls to `org.eclipse.jdt.internal.ui.startup.StartupListener.jdtuiIsAboutToStart()` do not deadlock or take a long time to finish. For example, think about what happens if one of the listeners that CodingTracker registers in `edu.illinois.codingtracker.listeners.JDTUIStartupListener.jdtuiIsAboutToStart()` depend on JDT UI? This is an important scenario because when these listeners are registered, JDT UI may not have started completely.
3. Make sure that `org.eclipse.jdt.internal.ui.JavaPlugin.start(BundleContext)` meets the contracts of `org.osgi.framework.BundleActivator.start(BundleContext)` and `org.eclipse.core.runtime.Plugin.start(BundleContext)`.
4. Compare using `org.osgi.framework.BundleListener` to get notified about the start up of JDT UI to modifying `org.eclipse.jdt.internal.ui.JavaPlugin.start(BundleContext)`.

**Comment by reprogrammer** [comment] 2011-07-11 19:18
@Wanderer777: See http://www.google.com/search?q=site:bugs.eclipse.org+eclipse+hangs+on+startup for simliar bugs reported to Eclipse. I'm suspicious about the invocations of the following two method while JDT UI is being loaded up because they seem to perform long running jobs.
1. `edu.illinois.codingtracker.listeners.SelectionListener#register()`
2. `edu.illinois.codingtracker.listeners.PartListener#register()`

I more concerned about `edu.illinois.codingtracker.listeners.SelectionListener.register()` because it runs a job using `Display#syncExec`. I believe this could potentially lead to a deadlock as described in [Eclipse Bug 325941](https://bugs.eclipse.org/bugs/show_bug.cgi?id=325941#c2).

**Comment by reprogrammer** [comment] 2011-07-11 21:14
@vazexqi and @Wanderer777:

Another potential cause of the deadlock could be `org.eclipse.epp.usagedata.internal.recording.uploading.UploadManager.watchedDirectoryLock`. Let's review the process of capturing the UDC data again to make sure there are no concurrency errors.

**Comment by reprogrammer** [comment] 2011-07-12 20:17
@Wanderer777:

Nick and I tried to reproduce the workspace corruption. We added a nonterminating loop to `org.eclipse.jdt.internal.ui.JavaPlugin.start(BundleContext)`. 

_EDIT_: We had to force Eclipse to quit because of the non-terminating loop.

As a result, Eclipse could no longer load up `org.eclipse.jdt.ui` during the startup. And, it refused the open the workspace later by showing the following message and provides the path to the associated workspace.

> Could not launch the application because the associated workspace is currently in use by another Eclipse application.

However, we were able to retrieve the workspace when we removed `.metadata/.lock` and opened the workspace with an unmodified Eclipse. I don't think if our participants meant the above error when they said their workspaces had got corrupted.

**Comment by reprogrammer** [comment] 2011-07-12 20:31
@Wanderer777:

We speculated that the deadlock during the data upload might have been because of a lazy uploading of `org.eclipse.jdt.ui`. However, I never managed to start up Eclipse without loading up `org.eclipse.jdt.ui` at start up. I tried Eclipse Helios SDK 3.6.2 and Eclipse Helios 3.6.0 for RCP and RAP Developers. I started these two instances of Eclipse on fresh workspaces and noticed that they both load up `org.eclipse.jdt.ui` while they start up. I remember you saying that `org.eclipse.jdt.ui` doesn't have to get loaded up during the start up of Eclipse. How can I make Eclipse not load `org.eclipse.jdt.ui` at its startup?

**Comment by reprogrammer** [comment] 2011-07-13 00:04
@Wanderer777:

Please see issue #282 for an example of using `SafeRunner` to run the code provided by an extension safely.

**Comment by Wanderer777** [comment] 2011-07-13 02:35
@reprogrammer: Close (not just hide) all Java-related views in Eclipse (e.g. editors, Package Explorer, etc.) and restart Eclipse. As a result, `org.eclipse.jdt.ui` would not be loaded at start up. Then, you can open any Java-related view, which would result in loading of `org.eclipse.jdt.ui`.

**Comment by reprogrammer** [comment] 2011-07-13 05:54
@Wanderer777: I closed all perspectives and restarted Eclipse. But, Eclipse still loaded up JDT during its start up. Then, I closed all perspectives other than the "Resource" perspective (See the [screenshot](http://s2.postimage.org/oip7ggu1/Eclipse_Resource_Perspective.png) of my Eclipse with just the "Resource" perspective). But, Eclipse continued to load up JDT during start up. What am I missing?

**Comment by Wanderer777** [comment] 2011-07-13 13:41
@reprogrammer: As I wrote above, close views, not perspectives. From your last screenshot I see Project Explorer view open, which is Java-related. Close it. I am not sure about Task, Task List, and Outline views, so try first closing just Project Explorer and restart Eclipse. If that does not help close all other views as well, and then restart. As about perspectives, as far as I remember, matters only what you have in the currently active perspective. So, if the current perspective does not have Java-related views, then even if other perspectives have them, `org.eclipse.jdt.ui` would not be loaded at Eclipse start up.

**Comment by reprogrammer** [comment] 2011-07-13 14:20
@Wanderer777: The "Project Explorer" view is not part of JDT (See [org.eclipse.ui.navigator.resources.ProjectExplorer](http://grepcode.com/file/repository.grepcode.com/java/eclipse.org/3.6.1/org.eclipse.ui.navigator/resources/3.4.201/org/eclipse/ui/navigator/resources/ProjectExplorer.java#ProjectExplorer)). But, as you said, when I close the "Project Explorer" view from the "Resource" perspective, JDT does no longer load up at startup. The "Project Explorer" view must have some dependency upon JDT.

**Comment by vazexqi** [comment] 2011-07-13 17:47
The problem of corrupted workspaces and deadlocks have been reported in Eclipse bugzilla. In reports of such bugs, I have noticed that the developers ask for thread dumps from Eclipse (http://wiki.eclipse.org/How_to_report_a_deadlock). 

So far we have not encountered any deadlock problems ourselves while running Eclipse and CodingSpectator but if we start up Eclipse following the instructions on that page, we might be able to get more data as we test CodingSpectator. In the rare event that we do see a deadlock, we would have the thread dump available for us to inspect.

Should we run Eclipse in that mode for our own development now?

**Comment by Wanderer777** [comment] 2011-07-14 01:27
@reprogrammer: I never said that Project Explorer view was part of JDT. I used the term "Java-related" in a broader sense, which includes dependencies on Java stuff (e.g. on JDT, as you confirmed in the post above).

**Comment by reprogrammer** [comment] 2011-07-14 01:35
@Wanderer777: I know. I was just surprised to learn that Package Explorer has a dependency on JDT. I expected the dependency to be the inverse.

**Comment by reprogrammer** [comment] 2011-07-14 01:38
@Wanderer777, @vazexqi: It looks nontrivial to me to prevent Eclipse from loading up JDT at its startup. How probable do you think it is that the participant who experienced the problem during uploading hadn't loaded up JDT at the start up of Eclipse?

**Comment by Wanderer777** [comment] 2011-07-14 14:01
@reprogrammer: Maybe this is not the only way to prevent JDT from loading at Eclipse startup. Besides, this problem in general looks extremely rare considering how many times we (and other participants so far) started Eclipse without noticing it. Considering this, it is possible that the participant experienced the rare scenario, when JDT is loaded lazily after Eclipse startup. 

At the same time, we might be missing some other scenarios, which lead to the same problem. I think that getting rid of `syncExec` calls as much as possible would reduce chances of any such scenario (including those that we can not imagine at this moment).

**Comment by reprogrammer** [comment] 2011-07-14 17:02
@vazexqi, @Wanderer777: So far, we haven't found a way to reproduce the deadlock. But, we might be able to increase the probability of the deadlock by making the [`Display#synExec`](https://github.com/vazexqi/CodingSpectator/blob/master/plug-ins/edu.illinois.codingtracker.recording/src/edu/illinois/codingtracker/listeners/SelectionListener.java#L33) job in `SelectionListener#register` long running.

**Comment by vazexqi** [comment] 2011-07-14 19:57
@Wanderer777: In `JDTUIStartupListener` there is the following comment:

<pre>
SelectionListener.register();
PartListener.register(); //should be registered after SelectionListener
</pre>


Why must PartListener be registered after SelectionListener?

**Comment by reprogrammer** [comment] 2011-07-14 23:36
eac1e1447b2111126e7d4ea25edddb1f343fed60 .. eb2a5e18271c1ae63da6f5f2dc5532031bd8ad3b in branch `initialize-codingtracker-asynchronously` initialize CodingTracker in JDT asynchronously. These commits make the following changes:
1. Use `BundleListener` to determine when to initialize CodingTracker.
2. Make `SelectionListener` use `Display#asyncExec` and busy wait for the active workbench window to become available rather than expecting it to be already available.
3. Wrap the call to `StartupListener#jdtuiIsAboutToStart()` in JDT UI by `SafeRunner`.

@Wanderer777: Can you review the commits in branch `initialize-codingtracker-asynchronously`?

**Comment by vazexqi** [comment] 2011-07-14 23:43
We should also read the section on ["Concurrency Do's and Don'ts"](http://wiki.eclipse.org/Architecture_Council/Top_Ten_Recommendations#Concurrency_Do.27s_and_Don.27ts) on the Eclipse wiki.

**Comment by Wanderer777** [comment] 2011-07-15 03:22
@reprogrammer and @vazexqi: The changes look good to me, thank you. I have two comments though:
- This one also answers the above question by @vazexqi about the need to register `PartListener` after `SelectionListener`. As you can see from the code of `PartListener#register`, it accesses variable `activeWorkbenchWindow`, which is assumed to be initialized by `SelectionListener#register`. Originally, it was ensured by the call to `syncExec` in `SelectionListener#register`. Now this call is changed to `asyncExec`, and I wonder if this still preserves the desired order of execution. From my tests, it works fine. But I am not sure that there is a guarantee that calls to `asyncExec` will be executed in the same order, in which they arrive. If the order preservation is guaranteed, our code is fine. If it is not, it may break with a `NullPointerException` in `PartListener#register` due to uninitialized `activeWorkbenchWindow`.
- The code of `JavaPlugin#notifyStartupListeners` may throw a runtime exception if it can not create executable extensions. We can either get rid of throwing a `RuntimeException` or put all the code inside a SafeRunner, which is, essentially, equivalent to silently suppressing `CoreException`, i.e. not re-throwing it as a `RuntimeException`, but has the drawback of stopping all notifications if a single executable extension is problematic. Therefore, I would prefer to just silently suppress `CoreException`. But considering that now `JavaPlugin#notifyStartupListeners` is called asynchronously, it maybe good to leave this exception such that we can see it in the error.log, which would help us to diagnose any possible problems. Moreover, we can make `SafeRunner#handleException` to record exceptions as well.

**Comment by reprogrammer** [comment] 2011-07-15 19:02
@Wanderer777:

Thanks for pointing out the dependency of `PartListener` on `SelectionListener` because of the shared state `BasicListener.activeWorkbenchWindow`. Is it OK to remove the shared state and recompute it whenever needed using `PlatformUI.getWorkbench().getActiveWorkbenchWindow()`?

By the way, `PlatformUI.getWorkbench()` could through an exception if the workbench has not been created yet. Is the workbench guaranteed to be initialized when CodingTracker registers its listeners?

I'm not sure if I understood your point about the exceptions in `org.eclipse.jdt.internal.ui.JavaPlugin.notifyStartupListeners()` correctly. Are you suggesting to log the `CoreException` in the error log or rethrow it as a `RuntimeException`? Note that `SafeRunner` logs the exceptions even if `SafeRunnable.handleException` is empty. See [`org.eclipse.core.runtime.SafeRunner.handleException(ISafeRunnable, Throwable)`](http://grepcode.com/file/repository.grepcode.com/java/eclipse.org/3.6.1/org.eclipse.equinox/common/3.6.0/org/eclipse/core/runtime/SafeRunner.java#SafeRunner.handleException%28org.eclipse.core.runtime.ISafeRunnable%2Cjava.lang.Throwable%29) for more details.

**Comment by Wanderer777** [comment] 2011-07-16 01:24
@reprogrammer:

Yes, it is OK to remove the shared state. We can use busy waiting in `PartListener` to get `activeWorkbenchWindow` the same way as we do in `SelectionListener`.

Thanks for pointing to this potential problem. I am not sure that this is guaranteed, but so far it did not cause any problems. To be on the safe side, we could try something similar to what `JavaPlugin#start` does, i.e. we could call `PlatformUI.isWorkbenchRunning()` before calling `PlatformUI.getWorkbench()`. But there are two concerns here: 1) According to the documentation of `PlatformUI.isWorkbenchRunning()`, it might return `true` when it is still unsafe to call `PlatformUI.getWorkbench()` (which by the way means that `jdt.ui` start up has a bug); 2) We need to make sure that the workbench is running, i.e. we can not just skip registering our listeners if it is not running. I am not sure if we should busy wait for it, or maybe if it is not running yet, then it is not supposed to run at all (i.e. a logic similar to what `JavaPlugin#start` does).

Oh, if `SafeRunner` records exceptions even if `SafeRunner.handleException` is empty, then we are fine, since this is what I was suggesting - we need to record all exceptions regardless of whether we suppress them or rethrow.

**Closed as completed** 2011-07-17 22:37 UTC
Labels: Bug
