### ISSUE TITLE
Failure in parsing a CodingTracker log file

### ISSUE THREAD

**Issue by reprogrammer** [vazexqi/CodingSpectator#291] opened 2011-08-05 08:16 UTC
`edu.illinois.codingtracker.operations.OperationDeserializer.getUserOperations(String)` failed to parse CodingTracker's log at `cs-509/25b9a309-33c7-4c9d-9919-776fb44e8614/1.0.0.201105300951/codingtracker/codechanges.txt`.

**Comment by Wanderer777** [comment] 2011-08-06 19:19
This problem is caused by the SVN merging marks that were introduced in the file as a result of a data upload that failed due to a conflict. Here are details on how SVN marks conflicting files: http://ariejan.net/2007/07/04/how-to-resolve-subversion-conflicts/

The file contains the following pattern:

```
<<<<<<< .mine
This is fun stuff!
=======
This is a documentation file
>>>>>>> .r6
```

We can fix this problem in two ways:
- To produce a full operation sequence which ignores the conflicting portion (which appeared due to restoring the Eclipse workspace to an earlier state), we need to remove the portion between === and >>> marks.
- In case we would like to replay the part that was later erased by restoring the Eclipse workspace, we need to remove the portion between <<< and === as well as everything following >>> 

This is a postprocessing fix that should be applied on the collected data after the participant stopped writing into this file (it could be applied on an intermediate file as well, but then it would have to be reapplied on the final file anyway).

**Comment by Wanderer777** [comment] 2011-10-09 19:58
The file was manually fixed and committed to the local repository.

**Closed as completed by Wanderer777** 2011-10-09 19:58 UTC
Labels: CodingTracker, Postprocessing
