### ISSUE TITLE
The last upload time doesn't get updated.

### ISSUE THREAD

**Issue by reprogrammer** [vazexqi/CodingSpectator#67] opened 2010-10-08 20:31 UTC
I uploaded my data manually. But, the last upload time didn't get updated.

**Comment by vazexqi** [comment] 2010-10-11 19:35
I cannot reproduce this problem on Windows or Mac. I haven't tried my Linux box yet.

This problem seems to happen to you even on a clean workspace right?

**Comment by vazexqi** [comment] 2010-10-11 21:15
I can reproduce the problem. And I think I know why now.

Basically we added disabled text fields to the preference page. This means that there is still some data in the text fields only that we can't edit it.

Here's the problem, when we click the "Upload Now" button, the timestamp is updated but not reflected on text fields.

Now, when we click the "OK", it tries to store whatever text is inside the disabled textfields. This means that it is storing the stale timestamp! And it's overriding the value that we had just updated!

Now, when we click cancel instead, we don't have this problem. The performCancel() method just doesn't store any of the values of the textfield.

**Comment by vazexqi** [comment] 2010-10-11 21:51
Resolved in e3bbc644735285ce5d297c49cca57adc715353a3

I used the IPropertyChangeListener event to listen to changes to the preference store and update appropriately.

Also since the text fields are disabled by default, I ensured that clicking "OK" will never store their values.

**Closed as completed by vazexqi** 2010-10-11 21:51 UTC
Labels: Data Uploading, Version-0.1
