### ISSUE TITLE
Release by 10/11/2011

### ISSUE THREAD

**Issue by reprogrammer** [vazexqi/CodingSpectator#307] opened 2011-08-14 16:40 UTC
The most important change in this release will be to postpone the writes into the watched folder.

This issue will list the changes in the upcoming release of CodingSpectator. Whenever you complete a feature or fix a bug, please add a comment to this issue briefly describing the change and the corresponding issue number.

**Comment by reprogrammer** [comment] 2011-10-09 00:05
@Wanderer777: I suggest that we release a new version of CodingSpectator that fixes the SVN conflict problem this weekend (10/9/2011). Could you please review the open issues that are assigned to you or related to CodingTracker and close or postpone them to the next milestone?

**Comment by reprogrammer** [comment] 2011-10-09 00:18
- Improve the reliability and performance of SWTBot tests by using wait instead of sleep commands (issue #226).
- Assumed that recording compilation problems doesn't change user experience (issue #211).
- Added the instructions for setting up the secure storage mechanism of Eclipse on different platforms (issue #265).
- Confirmed that CodingTracker works fine with the refresh on access feature of Eclipse Indigo (issue #266).
- Wrote several SQL queries to analyze the collected data and answer our research questions (issue #288).
- Developed an analyzer to generate a CSV report of refactorings followed by runs of programs and tests (issue #293).
- Modified a script to report the latest version of CodingSpectator each participant has used to submit data (issue #294).
- Modified a script to report the amount of data CodingTracker has collected from each participant (issue #316).
- Considered the committer in Subversion logs when finding the latest data submission of each participant (issue #296).
- Fixed the parser of refactoring histories to correctly deserialize the refactorings captured by systems with different locales (issue #298).
- Assumed that Subversion's complaints about files that have been added to the working copy but do not exist are because the participants have manipulated the working copy (issue #299).
- Added a SQL query to compare the usage frequencies of refactorings reported by UDC and CodingSpectator (issue #303).
- Decided not to conduct the awareness survey online (issue #315).
- Marked parts of the captured code snippets that the participants had selected to invoke refactorings (issue #317).
- Fixed a bug in the `logstocsv` program that truncated the `comments` attribute of refactorings (issue #320).
- Wrote a script to combine the CSV reports of the size and configuration time of refactorings (issue #322).
- Changed the maximum length of the first line of commit messages to 72 characters (issue #325).
- Captured invocations of the Infer Generic Type Arguments refactoring (issue #272).
- Buffered the CodingSpectator data outside the watched folder and copied it over before submissions (issue #287).
- Moved two SVN operations from Submitter#authenticateAndInitialize to Submitter#submit (issue #308).
- Made the submitter upload data even when the watched folder is outdated or has conflicts (issues #257, #309, and #311).
- Used an instance of Eclipse without CodingSpectator to resolve the issue with old `SubmitterListener`s (issue #326).
- Increased the versions of two JDT bundles to make CodingSpectator compatible with Eclipse Indigo SR1 (issues #327, #328).

**Comment by Wanderer777** [comment] 2011-10-09 20:05
- Implemented usage time analyzer (issue #321) and refactoring effects analyzer.
- Improved the replay speed of CodingTracker, also added the 'jump to' action (issue #314).
- Added postprocessor to fix the negative refactoring timestamps and updated all the broken sequences (issue #301).
- Implemented an automated converter from the old to the new API of refactoring operations and updated all the old sequences correspondingly in order to simplify the supported API (issue #300).
- Implemented a postprocessor that fixes spurious SVN commit operations (issue #241).
- Sped up registering of CodingTracker's listeners (issue #324).
- Updated older CodingTracker sequences to the new data format and committed them to the internal repository (issue #244).
- Investigated `NoSuchMethodError` thrown from `org.eclipse.compare.core` and established that it is not caused by CodingTracker (issue #253).
- Implemented support for conflict editors opened via 'Compare With' menu (issue #286).
- Manually fixed and committed to the local repository a sequence containing conflict markers (issue #291).
- Explained to @reprogrammer what is `FinishedRefactoringOperation.success` (issue #297).
- Extended the functionality of the 'Find' replay action to look for an operation with the closest timestamp if a precise match cannot be found (issue #313).

**Comment by reprogrammer** [comment] 2011-10-09 23:42
@Wanderer777:

Could you please add brief descriptions of the following issues to [your comment above](https://github.com/vazexqi/CodingSpectator/issues/307#issuecomment-2338436)?
- issue #244
- issue #253
- issue #286
- issue #291
- issue #297
- issue #313

**Comment by reprogrammer** [comment] 2011-10-11 20:14
@Wanderer777, @vazexqi, @rajkuma1:

The new unstable releases of CodingSpectator for Helios and Indigo are available at the following addresses:
- Helios: http://codingspectator.cs.illinois.edu/unstable-updates/helios/
- Indigo: http://codingspectator.cs.illinois.edu/unstable-updates/indigo/

Please upgrade your installations of CodingSpectator to the new unstable releases and let me know if you find any problems.

**Comment by Wanderer777** [comment] 2011-10-12 13:15
@reprogrammer: Should we implement support for Indigo SR1 in the upcoming release? If yes, I would rather test the release after all our changes to it.

**Comment by Wanderer777** [comment] 2011-10-12 14:35
@reprogrammer: Oh, I noticed that the Indigo SR1 installation problem was solved as part of another issue.

**Closed as completed** 2011-10-14 00:41 UTC
Labels: Release
